services:
  stev_google_cloud_translate.services.google_translator:
    class: Stev\GoogleCloudTranslateBundle\Services\GoogleTranslator
    arguments: ['@jms_translation.loader_manager','@logger','@jms_translation.file_writer','@stev_google_cloud_translate.services.catalogue_translator']

  stev_google_cloud_translate.services.google_translate_api:
    class: Stev\GoogleCloudTranslateBundle\Services\GoogleTranslateAPI
    arguments: ['%stev_google_cloud_translate.translate_api_config%']

  stev_google_cloud_translate.services.catalogue_translator:
    class: Stev\GoogleCloudTranslateBundle\Services\CatalogueTranslator
    arguments: [ '@stev_google_cloud_translate.services.google_translate_api', '@logger']